### ISSUE TITLE
week-start-date does not work

### ISSUE THREAD

**Issue by tugrulelmas** [mominsamir/smDateTimeRangePicker#150]
Hello,
week-start-date does not work with different locales. I could not set Monday as first day of week with locale "tr".
None of them `week-start-day="Monday"` and `week-start-day="Pazartesi"` work.

**Comment by oleg-demkovych** [comment]
I have it too.

**Comment by oscar09** [comment]
Is this error in the date range field? It works fine for me with date field. Also, I don't think the property supports locales. You need to provide the day in English.

**Comment by oscar09** [comment]
This error should be fixed in the latest master version. I only found the error on the date range field.

**Comment by oleg-demkovych** [comment]
Week start day still not working in **v2.0.11**. 
http://take.ms/y5gmB

`week-start-day="Monday"`

**Comment by oscar09** [comment]
The fix was not included in v2.0.11. It is in master version only. It will be available until next tag.
