### ISSUE TITLE
Formatting range-picker date some issues occur

### ISSUE THREAD

**Issue by salva-b** [mominsamir/smDateTimeRangePicker#3]
Hi! Awesome picker!
I'm trying to format date to "DD-MM-YYYY" on range-picker so when i select a start date like '10-02-2016' end date jumps to 'october' when needed to be 'february'.
Also, sometimes when selecting end date an error of 'invalid date' occurs.
Thx!

**Comment by mominsamir** [comment]
I have fixed date formatting issue, However i was not able to product invalid date, if you can provide me some ref, i can check and fix if its bug.

thanks for your feed back

**Comment by salva-b** [comment]
I think is in same way of date formatting. 
For example using format date of "DD-MM-YYYY" and selecting an start date of '26/03/2016' end date field jumps to year 2018 and any selected date returns 'invalid date'.
Maybe with your fix is working now. 
Thx again

**Comment by salva-b** [comment]
Hi Samir, I tested your fix and is working fine when selecting 'start date' but still not working when selecting 'end date' with format "DD-MM-YYYY" and selecting an start date like '26/03/2016'. Appears invalid date error.

**Comment by mominsamir** [comment]
HI One thing I noticed in your comment, You are trying to set date with separator "-" but your start date is separated by "/" this is what causing the invalid date issue.  either try both format and date with same  separator "-" or "/" but not both. this should resolve your issue.

**Comment by salva-b** [comment]
Hi, this is a typographic error. Im using format "DD-MM-YYYY" with format attribute of your component. I select start date manually with your datepicker.

**Comment by mominsamir** [comment]
Can you give me step by step how to reproduce error.

I am not able to produce error by following your comment.

**Comment by salva-b** [comment]
Try this:
        <sm-range-picker-input 
            md-no-float class="md-block" 
            fname="dayOfPay" 
            lable="date range"
            form="empForm"
            value="vm.employee.dateOfPay" 
            is-required="{{true}}" 
            format="DD-MM-YYYY"
            mode="date-time" 
            week-start-day="Monday">
            </sm-range-picker-input> 
Select custom range. Then select a start date of '26 March 2016'. So then calendar jumps to 'end date' in 2018 and any date selected returns 'invalid date'.

**Comment by mominsamir** [comment]
OK Thanks i will check i got it

**Comment by mominsamir** [comment]
Please pull new version 1.0.0b and now its fixed [plunkr](http://plnkr.co/edit/2ePb5nf8vH71iH5byP7q?p=preview)

**Comment by mominsamir** [comment]
Close issue if its fixed

**Comment by salva-b** [comment]
Hi Samir,
can't test it. Minified js file isn't good. I think html is included in file
thx

**Comment by salva-b** [comment]
Great! its working Samir. 
You are best! Thx!!

**Comment by mominsamir** [comment]
Check the plunkr
